<?php

define('DPO_FORM_ELEMENT_PREFIX', 'dpo--');
/**
 * Implements hook_menu().
 *
 * @return array
 */
function display_pattern_options_menu(){
    return _display_pattern_options_add_ajax_endpoints();
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param $form_state
 */
function display_pattern_options_form_ctools_node_content_type_edit_form_alter(&$form, &$form_state){

    _display_pattern_options_pane_form_alter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param $form_state
 */
function display_pattern_options_form_views_ui_edit_display_form_alter(&$form, &$form_state){

    _display_pattern_options_views_form_alter($form, $form_state);
}

/**
 * Implements hook_panels_pane_content_alter().
 *
 * @param $content
 * @param $pane
 * @param $args
 * @param $contexts
 */
function display_pattern_options_panels_pane_content_alter($content, $pane, $args, $contexts){
    _display_pattern_options_expose_custom_pane_config($content, $pane);
}

/**
 * Add display_pattern_options value (from panel pane setting) to node object so it available in preprocess
 *
 * @param $content
 * @param $pane
 */
function _display_pattern_options_expose_custom_pane_config($content, $pane){
    if (array_key_exists('display_options', $pane->configuration)) {
        $content->content['#node']->display_pattern_options = $pane->configuration['display_pattern_options'];
    }
}

/**
 * Implements hook_entity_info_alter().
 */
function display_pattern_options_entity_info_alter(&$entity_info) {
    _display_pattern_options_add_custom_view_modes($entity_info);
}

/**
 * Add custom view modes (without using entity view mode module)
 *
 * NOTE: node view mode disabled by default
 * use display_pattern_options.install to enable per bundle
 *
 * @param $entity_info
 */
function _display_pattern_options_add_custom_view_modes(&$entity_info){

    $entities = _display_pattern_options_get_view_mode_config();

    foreach ($entities as $entity_type => $bundles) {

        foreach ($bundles as $bundle_type => $view_modes) {

            foreach ($view_modes as $view_mode){
                $entity_info[$entity_type]['view modes'][$view_mode] = array(
                    'label' => t(ucfirst($view_mode)),
                    'custom settings' => $entity_type == 'node' ? FALSE : TRUE,
                );
            }
        }
    }
}

/**
 * Implements hook_entity_prepare_view().
 *
 *
 * @param $entities
 * @param $type
 * @param $langcode
 */
function display_pattern_options_entity_prepare_view($entities, $type, $langcode){
    _display_pattern_options_expose_custom_view_config($entities);
}

/**
 * Add display_pattern_options value (from view setting) to node object so it available in preprocess
 *
 * see display_pattern_options_preprocess_node() where these are added to html as classes
 *
 * @param $entities
 */
function _display_pattern_options_expose_custom_view_config($entities){

    foreach ($entities as &$entity) {

        if (property_exists($entity, 'view')) {

            $entity->display_pattern_options = array();

            // get default view display settings
            foreach($entity->view->display['default']->display_options['row_options'] as $label => $option) {

                if (strpos($label, DPO_FORM_ELEMENT_PREFIX) !== false) {
                    $entity->display_pattern_options[$label] = $option;
                }

            }

            // overwrite with current view display settings - if available (there is prob a better way of doing this)
            foreach($entity->view->display[$entity->view->current_display]->display_options['row_options'] as $label => $option) {
                if (strpos($label, DPO_FORM_ELEMENT_PREFIX) !== false) {
                    $entity->display_pattern_options[$label] = $option;
                }

            }
        }
    }
}

/**
 * Add custom ajax endpoints
 *
 * @return array
 */
function _display_pattern_options_add_ajax_endpoints(){

    $items = array();

    $items['display_pattern_options_ajax_menu_item'] = array(
        'page callback' => '_display_pattern_options_ajax_callback',
        // Ensure correct format for rendered content
        'delivery callback' => 'ajax_deliver',
        'access callback' => TRUE,
        // Ensure correct theme is used for custom ajax path
        'theme callback' => 'ajax_base_page_theme',
        'type' => MENU_CALLBACK
    );

    return $items;
}

/**
 * Add display_pattern_options to view mode forms
 *
 * @param $form
 * @param $form_state
 */
function _display_pattern_options_pane_form_alter(&$form, &$form_state){

    $default_option = $form_state['conf']['display_pattern_options'];

    if (array_key_exists('build_mode', $form_state['input'])) {
        $view_mode = $form_state['input']['build_mode'];
    } else{
        $view_mode = $form['build_mode']['#default_value'];
    }

    $view_mode_options = _display_pattern_options_get_options_by_view_mode($view_mode);

    foreach ($view_mode_options as $label => $options) {
        _display_pattern_options_add_form_element($form, $label, $options, $default_option);
    }
}

/**
 * Add display_pattern_options element to specified form or the parent element (within form) if specified
 *
 * @param $form
 * @param $label
 * @param $options
 * @param $default
 * @param bool $parent
 */
function _display_pattern_options_add_form_element(&$form, $label, $options, $default, &$parent=false){

    if (!$parent) {
        $parent = &$form;
    }

    $parent[DPO_FORM_ELEMENT_PREFIX. $label] = _display_pattern_options_build_form_element($label, $options, $default);

    $form['#submit'][] = '_display_pattern_options_form_ctools_node_content_type_edit_form_submit';
}

/**
 * Build a display pattern option form element
 *
 * @param $label
 * @param $options
 * @param $default
 * @param bool $id
 * @return array
 */
function _display_pattern_options_build_form_element($label, $options, $default=false, $id=false){

    $element = array(
        '#title' => $label,
        '#type' => 'select',
        '#description' => 'Select display pattern options for this build mode',
        '#options' => array('default' => '- Default -') + $options,
        '#default_value' => $default ? $default : 'default',
    );

    if ($id) {
        // this adds id (that is normally auto added)
        // when we manually build element for ajax replace
        $element['#id'] = $id;
        $element['#name'] = 'row_options['. DPO_FORM_ELEMENT_PREFIX . $label . ']';
    }

    return $element;
}

/**
 * Add display_pattern_options to view mode forms
 *
 * @param $form
 * @param $form_state
 */
function _display_pattern_options_views_form_alter(&$form, &$form_state){

    if ($form_state['section'] != 'row_options') {
        return;
    }

    $form['options']['row_options']['view_mode']['#ajax'] = array(
        // callback wont work here (ctools)
        // so we provide custom path
        // which provides callback
        'path' => 'display_pattern_options_ajax_menu_item',
    );

    if (array_key_exists('row_options', $form_state['input'])) {
        $view_mode = $form_state['input']['row_options']['view_mode'];
    } else{
        $view_mode = $form['options']['row_options']['view_mode']['#default_value'];
    }

    $view_mode_options = _display_pattern_options_get_options_by_view_mode($view_mode);

//    $form['options']['row_options']['dpo'] = array(
//        '#type' => 'container',
//        '#attributes' => array('class'=>array('js-replace-container')),
//        //'content' => array()
//    );

    $i = 0;
    $len = count($view_mode_options);
    foreach ($view_mode_options as $label => $options) {

        // NOTE: Assignment(=) not comparison(==)
        // current view display
        if (!$default_option = $form_state['view']->display[$form_state['view']->current_display]->display_options['row_options'][DPO_FORM_ELEMENT_PREFIX. $label]) {
           // fallback to default view display
            $default_option = $form_state['view']->display['default']->display_options['row_options'][DPO_FORM_ELEMENT_PREFIX. $label];
        }

        _display_pattern_options_add_form_element($form, $label, $options, $default_option, $form['options']['row_options']);

        // add html wrapper around ALL option elements to be replaced in ajax callback
        // NOTE: cannot add to render array as this will affect id and name attributes and values will not get saved as part of row options
        if ($i == 0) {
            $form['options']['row_options'][DPO_FORM_ELEMENT_PREFIX. $label]['#prefix'] = '<div class="js-replace-container">';
        }

        if ($i == $len-1) {
            $form['options']['row_options'][DPO_FORM_ELEMENT_PREFIX. $label]['#suffix'] = '</div>';
        }

        $i++;
    }
    //@todo: make this betterer
    if ($i == 0) {
        $form['options']['row_options']['placeholder'] = array(
            '#type' => 'markup',
            '#markup' => '<div class="js-replace-container"></div>'
        );
    }
}

/**
 * Custom ajax callback
 *
 * replace all display_pattern_option select elements with those applicable to selected view_mode
 * when view_mode element is changed
 *
 * @return array
 */
function _display_pattern_options_ajax_callback(){

    $commands = array();

    $view_mode_options = _display_pattern_options_get_options_by_view_mode($_POST['row_options']['view_mode']);

    $elements = array(
        '#type' => 'container',
        '#attributes' => array('class'=>array('js-replace-container')),
        'content' => array()
    );

    // replace ALL option select elements
    // this avoids the problem where we may be trying to replace elements that dont exist
    // because the first view mode that loaded did not have the options that the subsequently selected view mode has
    foreach ($view_mode_options as $label => $options) {
        $elements['content'][] = _display_pattern_options_build_form_element($label, $options, false, 'edit-row-options-'. $label);
    }

    $commands[] = ajax_command_replace('.js-replace-container', drupal_render($elements));

    return array(
        '#type' => 'ajax',
        '#commands' => $commands
    );
}

/**
 * Custom submit function to store added config values
 *
 * @param $form
 * @param $form_state
 */
function _display_pattern_options_form_ctools_node_content_type_edit_form_submit($form, &$form_state) {
    $form_state['conf']['display_pattern_options'] = $form_state['values']['display_pattern_options'];
}

/**
 * Defines custom view_modes by entity
 *
 * @return array
 */
function _display_pattern_options_get_view_mode_config(){
    return array(
        // entity type
        'node' => array(
            // bundle
            'page' => array(
                //  view mode / build mode / content pattern
                'hero',
                'promo'
            ),
            // bundle
            'article'=> array(
                //  view mode / build mode / content pattern
                'promo'
            )
        ),

        // entity type
        'user' => array(
            // bundle
            'user'=> array(
                //  view mode / build mode / content pattern
                'promo'
            )
        ),

        // entity type
        'taxonomy_term' => array(
            // bundle
            'taxonomy_term'=> array(
                //  view mode / build mode / content pattern
                'promo'
            )
        )
    );
}

/**
 * Get available view_mode_options by view_mode
 *
 * @param $view_mode
 * @return mixed
 */
function _display_pattern_options_get_options_by_view_mode($view_mode){
    $config = _display_pattern_options_get_options_config();

    return $config[$view_mode];
}

/**
 * Defines view_mode_options available for each view_mode
 *
 * @return array
 */
function _display_pattern_options_get_options_config(){
    return array(
        // view mode
        'hero' => array(
            // modifiers
            'colour' => array(
                'red' => 'Red',
                'green' => 'Green',
                'blue' => 'Blue'
            ),
            'align' => array(
                'left' => 'Left',
                'right' => 'Right',
            )
        ),
        // theme
        'promo' => array(
            // modifiers
            'colour' => array(
                'red' => 'Red',
                'green' => 'Green'
            )
        )
    );
}

/**
 * Enable custom view modes for selected bundles
 *
 * NOTE:
 * called in .install
 * see display_pattern_options.module for _display_pattern_options_get_config()
 */
function _display_pattern_options_enable_view_modes_by_bundle(){

    $entities = _display_pattern_options_get_view_mode_config();

    foreach ($entities as $entity_type => $bundles) {
        foreach ($bundles as $bundle_type => $view_modes) {
            $settings = NULL;
            $settings = field_bundle_settings($entity_type, $bundle_type);
            foreach ($view_modes as $view_mode){
                $settings['view_modes'][$view_mode]['custom_settings'] = TRUE;
            }
            field_bundle_settings($entity_type, $bundle_type, $settings);
        }
    }
}


// @TODO: might be useful??
//function display_pattern_options_entity_view_mode_alter(&$view_mode, $context) {
//    // For nodes, change the view mode when it is teaser.
//    if ($context['entity_type'] == 'node' && $view_mode == 'teaser') {
//        $view_mode = 'my_custom_view_mode';
//    }
//}

/**
 * Implements hook_preprocess_node().
 *
 * @param $variables
 */
function display_pattern_options_preprocess_node(&$variables) {
    // Add view-mode class to nodes
    $variables['classes_array'][] = drupal_html_class('content-pattern--' . $variables['type']);
    $variables['classes_array'][] = drupal_html_class('display-pattern--' . $variables['view_mode']);

    if (array_key_exists('display_pattern_options', $variables)) {

        foreach ($variables['display_pattern_options'] as $key => $value) {
            $variables['classes_array'][] = drupal_html_class('display-pattern-options-'. $key .'--'. $value);
        }
    }
}